# Example configuration.yaml entry
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /config
    - type: memory_use_percent
    - type: swap_use_percent
    - type: last_boot
    - type: ipv4_address
      arg: eth0
    - type: packets_in
      arg: eth0
    - type: packets_out
      arg: eth0
    - type: throughput_network_in
      arg: eth0
    - type: throughput_network_out
      arg: eth0
    - type: processor_temperature
    - type: processor_use
    - type: load_15m
