# Configure a default setup of Home Assistant (frontend, api, etc)
# Including Directories
# !include_dir_list will return the content of a directory as a list with each file content being an entry in the list. The list entries are ordered based on the alphanumeric ordering of the names of the files.
# !include_dir_named will return the content of a directory as a dictionary which maps filename => content of file.
# !include_dir_merge_list will return the content of a directory as a list by merging all files (which should contain a list) into 1 big list.
# !include_dir_merge_named will return the content of a directory as a dictionary by loading each file and merging it into 1 big dictionary.
homeassistant:
  packages: !include_dir_named packages

alert: !include_dir_merge_named alerts/

camera: !include_dir_list entities/cameras

group: !include_dir_list entities/group

#HACS  Add-On
battery_notes:

light: !include_dir_list entities/lights

#localtuya: !include localtuya.yaml

media_player: !include entities/media_players.yaml

notify: !include notify.yaml

proximity:
  home:
    devices:
      - device_tracker.rodney_iphone
      - device_tracker.rodney_iphone_icloud
      - device_tracker.gina_iphone
      - device_tracker.gina_iphone_icloud
    tolerance: 10
    unit_of_measurement: 'mi'
  work:
    devices:
      - device_tracker.rodney_iphone
      - device_tracker.rodney_iphone_icloud
      - device_tracker.work_phone
    tolerance: 10
    unit_of_measurement: 'mi'

sensor: !include_dir_merge_list entities/sensors

switch: !include_dir_merge_list entities/switches

# Text to speech
tts:
  - platform: google_translate

shell_command:
  mount_music_folder: "mkdir -p /media/nas;mount -t cifs -o vers=3.0,noserverino,username=!secret sysnology_user,password=!secret synology_pass,domain=WORKGROUP //synology.local/music /media/nas"