###############################################################################
#  @author         :  Rodney Smith
#  @date           :  07/04/2023
#  @package        :  Tablet Dashboard
#  @description    :  My Tablet Dashboard in yaml
###############################################################################
kiosk_mode:
  mobile_settings:
    hide_header: true
views:
  - theme: Backend-selected
    title: Home
    visible:
      - user: d2fcb98b323e47cfa359ef19282d91e9
      - user: 0490f5256ca34bffa055bab3a33e0f6e
    type: custom:grid-layout
    badges: []
    cards:
      - type: custom:mushroom-chips-card
        chips:
          - type: weather
            entity: weather.local
            show_conditions: true
            show_temperature: true
          - type: alarm-control-panel
            entity: alarm_control_panel.blink_home
            name: blink
            content_info: state
          - type: alarm-control-panel
            entity: alarm_control_panel.alarmo
            name: Alarmo
            content_info: state
        alignment: center
      - type: vertical-stack
        cards:
          - type: custom:mushroom-template-card
            primary: |-
              {% set time = now().hour %}
              {% if (time >= 18) %}
                Good Evening, {{user}}!
              {% elif (time >= 12) %}
                Good Afternoon, {{user}}!
              {% elif (time >= 5) %}
                Good Morning, {{user}}!
              {% else %}
                Hello, {{user}}!
              {% endif %}
          - type: horizontal-stack
            cards:
              - type: custom:mushroom-template-card
                primary: House
                icon: mdi:home
                icon_color: blue
                tap_action:
                  action: navigate
                  navigation_path: /home-dash/house
                layout: vertical
              - type: custom:mushroom-template-card
                primary: Lights
                icon: mdi:lightbulb
                layout: vertical
                icon_color: |-
                  {% if is_state('light.of_light_zb', 'on') 
                  or is_state('light.wled_soundreactive', 'on')
                  or is_state('light.left_floor_lamp', 'on')
                  or is_state('light.right_floor_lamp', 'on')
                  or is_state('light.light_strip_10fe', 'on')
                  or is_state('light.light_strip_831a', 'on')
                  or is_state('light.h61e1_led_strip', 'on') 
                  or is_state('light.funhouse_light', 'on')
                  or is_state('light.mb_ceiling_lights', 'on')
                  or is_state('light.gina_nightstand', 'on')
                  or is_state('light.rodney_nightstand', 'on')
                  or is_state('light.h61e0_gina_led_strip', 'on')
                  or is_state('light.h61e0_rodney_led_strip', 'on')
                  or is_state('light.br1_ceiling_lights', 'on')
                  or is_state('light.bedroom1_light', 'on')
                  or is_state('light.br2_ceiling_lights', 'on')
                  or is_state('light.bedroom2_light', 'on')
                  or is_state('light.gina_light', 'on')
                  or is_state('light.rodney_light', 'on')
                  or is_state('light.kitchen_lights', 'on')
                  or is_state('light.dining_room', 'on')
                  or is_state('light.foyer', 'on')
                  or is_state('light.hl_bulb_linen', 'on')
                  or is_state('light.entrance', 'on')
                  or is_state('light.side_porch_1', 'on')
                  or is_state('light.side_porch_2', 'on')
                  or is_state('light.front_porch_1', 'on')
                  or is_state('light.front_porch_2', 'on')
                  or is_state('light.first_light', 'on') 
                  or is_state('switch.mj_s01_b71a3c', 'on') %}
                    amber
                  {% else %}
                    grey
                  {% endif %}
                tap_action:
                  action: navigate
                  navigation_path: /home-dash/lights
              - type: custom:mushroom-template-card
                primary: Cameras
                icon: mdi:camera
                icon_color: green
                layout: vertical
                tap_action:
                  action: navigate
                  navigation_path: /home-dash/cameras
              - type: custom:mushroom-template-card
                icon_color: red
                primary: Smoker
                layout: vertical
                tap_action:
                  action: navigate
                  navigation_path: /home-dash/smoker
                icon: mdi:grill
              - type: custom:mushroom-template-card
                primary: Vacuum
                icon: mdi:robot-vacuum
                layout: vertical
                tap_action:
                  action: navigate
                  navigation_path: /home-dash/vacuum
                icon_color: ''
              - type: custom:mushroom-template-card
                primary: Calendar
                icon: mdi:calendar
                icon_color: amber
                layout: vertical
                tap_action:
                  action: navigate
                  navigation_path: /home-dash/calendar
              - type: custom:mushroom-template-card
                primary: Stocks
                icon: mdi:cash
                layout: vertical
                tap_action:
                  action: navigate
                  navigation_path: /home-dash/stocks
                icon_color: ''
              - type: custom:mushroom-template-card
                primary: Sports
                icon: mdi:baseball-bat
                icon_color: green
                layout: vertical
                tap_action:
                  action: navigate
                  navigation_path: /home-dash/sports
              - type: custom:mushroom-template-card
                primary: HA
                icon: mdi:home-assistant
                layout: vertical
                icon_color: |-
                  {% if is_state('update.home_assistant_core_update', 'on') 
                     or is_state('update.home_assistant_operating_system_update', 'on')
                     or is_state('update.home_assistant_supervisor_update', 'on')
                     or is_state('update.esphome_update', 'on')
                     or is_state('update.file_editor_update', 'on')
                     or is_state('update.git_pull_update', 'on')
                     or is_state('update.grafana_update', 'on')
                     or is_state('update.influxdb_update', 'on')
                     or is_state('update.mariadb_update', 'on')
                     or is_state('update.phpmyadmin_update', 'on')
                     or is_state('update.samba_share_update', 'on')
                     or is_state('update.studio_code_server_update', 'on') 
                     or is_state('update.tasmobackup_update', 'on') 
                     or is_state('update.advanced_ssh_web_terminal_update', 'on')
                     or is_state('update.home_assistant_google_drive_backup_update', 'on')
                     or is_state('update.matter_server_update', 'on')
                     or is_state('update.piper_update', 'on')
                     or is_state('update.whisper_update', 'on')
                     or is_state('update.zigbee2mqtt_update', 'on') %}
                     orange
                  {% elif is_state('update.pi_hole_core_update_available', 'on')
                     or is_state('update.pi_hole_ftl_update_available', 'on')
                     or is_state('update.pi_hole_web_update_available', 'on') %}
                     pink
                  {% elif is_state('update.hacs_update', 'on') %}
                     yellow
                  {% else %}
                     blue
                  {% endif %}
                tap_action:
                  action: navigate
                  navigation_path: /home-dash/home-assistant
              - type: custom:mushroom-template-card
                icon_color: red
                primary: Earth
                layout: vertical
                tap_action:
                  action: navigate
                  navigation_path: /home-dash/earth
                icon: mdi:earth
      - type: vertical-stack
        cards:
          - type: custom:mushroom-title-card
            subtitle: Rooms
          - type: grid
            columns: 4
            square: false
            cards:
              - type: custom:mushroom-template-card
                primary: Office
                secondary: >-
                  {{states('sensor.office_temperature')}}°F 
                  {{states('sensor.office_lux')}} lux
                entity: switch.of_light_zb
                tap_action:
                  action: navigate
                  navigation_path: /home-dash/office
                hold_action:
                  action: toggle
                icon: mdi:desk
                icon_color: |-
                  {% if is_state('light.of_light_zb', 'on') 
                  or is_state('light.wled_soundreactive', 'on')
                  or is_state('light.left_floor_lamp', 'on')
                  or is_state('light.right_floor_lamp', 'on')
                  or is_state('light.light_strip_10fe', 'on')
                  or is_state('light.h61e1_led_strip', 'on') %}
                    amber
                  {% endif %}
              - type: custom:mushroom-template-card
                primary: Living Room
                secondary: >-
                  {{states('sensor.livingroom_temperature')}}°F
                  {{states('sensor.lr_motion_illuminance_lux')}} lux
                entity: light.living_room_lamps
                tap_action:
                  action: navigate
                  navigation_path: /home-dash/livingroom
                hold_action:
                  action: toggle
                icon: mdi:sofa
                icon_color: |-
                  {% if is_state('light.living_room_lamps', 'on') %}
                    amber
                  {% endif %}
              - type: custom:mushroom-template-card
                primary: Main Bedroom
                secondary: >-
                  {{states('sensor.mainbedroom_temperature')}}°F
                  {{states('sensor.main_bedroom_lux')}} lux
                entity: light.main_bedroom_nightstands
                tap_action:
                  action: navigate
                  navigation_path: /home-dash/mainbedroom
                hold_action:
                  action: toggle
                icon: mdi:bed
                icon_color: |-
                  {% if is_state('light.main_bedroom_light', 'on')
                  or is_state('light.main_bedroom_nightstands', 'on')
                  or is_state('light.gina_led_strip', 'on')
                  or is_state('light.rodney_led_strip', 'on') %}
                    amber
                  {% endif %}
              - type: custom:mushroom-template-card
                primary: Kitchen
                secondary: >-
                  {{states('sensor.kitchen_temperature')}}°F
                  {{states('sensor.kn_motion_illuminance_lux')}} lux
                entity: light.kitchen_lights
                tap_action:
                  action: navigate
                  navigation_path: /home-dash/kitchen
                hold_action:
                  action: toggle
                icon: mdi:knife
                icon_color: |-
                  {% if is_state('light.kitchen_lights', 'on') %}
                    amber
                  {% endif %}
              - type: custom:mushroom-template-card
                primary: Guest Room1
                secondary: >-
                  {{states('sensor.br1_temperature')}}°F
                  {{states('sensor.br1_motion_illuminance_lux')}} lux
                entity: light.br1_ceiling_lights
                tap_action:
                  action: navigate
                  navigation_path: /home-dash/guest1
                hold_action:
                  action: toggle
                icon: mdi:bed-outline
                icon_color: |-
                  {% if is_state('light.br1_ceiling_lights', 'on')
                  or is_state('light.bedroom1_light', 'on') %}
                    amber
                  {% endif %}
              - type: custom:mushroom-template-card
                primary: Guest Room2
                secondary: >-
                  {{states('sensor.br2_temperature')}}°F
                  {{states('sensor.br2_motion_illuminance_lux')}} lux
                entity: light.br2_ceiling_lights
                tap_action:
                  action: navigate
                  navigation_path: /home-dash/guest2
                hold_action:
                  action: toggle
                icon: mdi:bed-outline
                icon_color: |-
                  {% if is_state('light.br2_ceiling_lights', 'on')
                  or is_state('light.bedroom2_light', 'on') %}
                    amber
                  {% endif %}
              - type: custom:mushroom-template-card
                primary: Outside
                secondary: >-
                  {{states('sensor.outside_temperature')}}°F
                  {{states('weather.local')}} - Inside
                  {{states('sensor.living_space_temperature')}}°F 
                entity: group.outside_lights
                tap_action:
                  action: navigate
                  navigation_path: /home-dash/patio
                hold_action:
                  action: toggle
                icon: mdi:forest
                icon_color: |-
                  {% if is_state('light.entrance', 'on')
                     or is_state('light.front_porch_1', 'on')
                     or is_state('light.front_porch_2', 'on')
                     or is_state('light.side_porch_1', 'on')
                     or is_state('light.side_porch_2', 'on')
                     or is_state('light.first_light', 'on')
                     or is_state('switch.mj_s01_b71a3c', 'on') %}
                     amber
                  {% endif %}
          - type: grid
            columns: 4
            square: false
            cards:
              - type: custom:mushroom-entity-card
                entity: input_boolean.dogs_fed
                tap_action:
                  action: toggle
              - type: custom:mushroom-entity-card
                entity: input_boolean.switch_dogs
                tap_action:
                  action: toggle
              - type: custom:mushroom-entity-card
                entity: input_boolean.rodney_pill_reminder
                tap_action:
                  action: toggle
              - type: custom:mushroom-entity-card
                entity: input_boolean.gina_pill_reminder
                tap_action:
                  action: toggle
              - type: custom:mushroom-entity-card
                entity: input_boolean.guest_mode
                tap_action:
                  action: toggle
title: Tablet
