substitutions:
  name: esp32c3-070288
  friendly_name: Office ESP32C3 mmwave
  occupancy_delay_off: "15s"

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32c3

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret esp32c3_070288

ota:
  password: !secret esphome_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret ip_esp32c3_070288
    gateway: !secret ip_gateway
    subnet: !secret ip_subnet
    dns1: !secret ip_dns
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${name}_AP
    password: !secret wifi_ap_pass
    ap_timeout: 3min

captive_portal:

uart:
  baud_rate: 115200
  rx_pin: 20
  tx_pin: 21

sensor:
  - platform: custom
    lambda: |-
      auto mmwave = new MMWaveSensor();
      App.register_component(mmwave);
      return {mmwave->presence_output};
    sensors:
      - name: "mmWave Sensor Presence"
        unit_of_measurement: "people"
        accuracy_decimals: 0
        icon: mdi:radiobox-marked
