substitutions:
  name: esp32-bluetooth-proxy-9910b8
  friendly_name: Office Bluetooth Proxy

packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret ip_btproxy_9910b8
    gateway: !secret ip_gateway
    subnet: !secret ip_subnet
    dns1: !secret ip_dns
  ap: 
    ssid: ${name}_AP
    password: !secret wifi_ap_pass
    ap_timeout: 3min

api:
  encryption:
    key: !secret btproxy_9910b8

ota:
  password: !secret esphome_ota