###############################################################################
#  @author         :  Rodney Smith
#  @date           :  03/14/2022
#  @package        :  Announcements
#  @description    :  Daily Announcements.
#                     This was borrowed from SlackerLabs
#  https://github.com/thejeffreystone/homeassistant-config/blob/main/config/packages/announcements.yaml
###############################################################################
###############################
# input_datetime - So the time report automation fires can be set in the UI
###############################
input_datetime:
  morning_report:
    name: Morning Report
    has_date: false
    has_time: true
  nightly_report:
    name: Nightly Report
    has_date: false
    has_time: true
  daily_report:
    name: Daily Report
    has_date: false
    has_time: true
  audible_notification_on:
    name: Audible Notifications On
    has_date: false
    has_time: true
  audible_notification_off:
    name: Audible Notifications Off
    has_date: false
    has_time: true

################################
# Announcment Automation - fires at the time of the above input_datetimes
################################
automation:
  - id: 1d8f396a-f6ec-460d-97e3-d11900418f95
    alias: Good Morning Report
    initial_state: true
    trigger:
      - platform: state
        entity_id: binary_sensor.office_occupancy
        to: "on"
    condition:
      - condition: time
        after: "06:45:00"
        before: "08:00:00"
      - condition: state
        entity_id: input_boolean.good_morning_report
        state: "off"
    action:
      - service: script.morning_briefing
        #    - service: script.twitter_notify
        data:
          message: >-
            {{ [ "I just provided a morning briefing including weather, and traffic
            conditions, and other things that ensure the residents of Anchorage House know what to expect today.",
                  "Time for the daily update. It was like that scene in Ironman where JARVIS gives the daily briefing but no one was listening. ",
                  "I have prepared a safety briefing to present to my residents but they would just ignore it.",
                  "Do you like to be prepared for the day? So do my residents. So I provided them with an update on whats happening today.",
                  "Sometimes I just like to be snarky, but this morning I decided to just tell everyone what is going on in the world.",
                  "#Homeassistant gives me the ability to make daily announcements like the one I just did using #Amazon Polly.",
                  "Each day at this time I provide the residents of this house an update that includes everything they need to know about the upcoming day. But with more snark."
                ] | random }}
      - service: input_boolean.turn_on
        entity_id: input_boolean.good_morning_report

  - id: e8580ba4-fa76-4185-818b-fba3c3cea41c
    alias: Master Bedroom Report
    initial_state: true
    trigger:
      platform: time
      at: input_datetime.daily_report
    condition:
      condition: state
      entity_id: binary_sensor.workday_sensor
      state: "on"
    action:
      - service: script.morning_wakeup_report

  - id: e1cb2f28-0423-11eb-adc1-0242ac120002
    alias: Rodney Event Starting soon
    trigger:
      - platform: state
        entity_id: calendar.rodney_events
        attribute: offset_reached
        to: True
    action:
      - service: script.status_annc
        data:
          who: "{{ states.sensor.room_presence.state }}"
          call_interuption: 1
          call_rodney_events: 1
      - service: script.notify_text
        data_template:
          who: "all_ios"
          message: Rodney has {{ states.calendar.rodney_events.attributes.message }} in 45 minutes.

  - id: 3cfe5e98-019c-4d95-a98c-8265ade12469
    alias: Gina Event Starting soon
    trigger:
      - platform: state
        entity_id: calendar.gina_events
        attribute: offset_reached
        to: True
    action:
      - service: script.status_annc
        data:
          who: "{{ states.sensor.room_presence.state }}"
          call_interuption: 1
          call_gina_events: 1
      - service: script.notify_text
        data_template:
          who: "all_ios"
          message: Gina has {{ states.calendar.gina_events.attributes.message }} in 45 minutes.
