##############################################################################
#  @author         :  Rodney Smith
#  @date           :  06/22/2022
#  @package        :  BHyve
#  @description    :  Orbit BHyve component for Home Assistant.
#                                  https://github.com/sebr/bhyve-home-assistant
###############################################################################
bhyve:
  username: !secret bhyve_user
  password: !secret bhyve_pass

#sensor:
#  - platform: bhyve

#switch:
#  - platform: bhyve

#binary_sensor:
#  - platform: bhyve

automation:
  - alias: BHyve next watering & rain delay finishing updater
    trigger:
      - platform: state
        entity_id: switch.patio_plants_zone
      - platform: homeassistant
        event: start
    action:
      - service: python_script.bhyve_next_watering
        data:
          entity_id: switch.patio_plants_zone
