###############################################################################
#  @author         :  Rodney Smith
#  @date           :  08/14/2023
#  @package        :  Occupancy
#  @description    :  Create template sensors that just need a single sensor to
#                     trigger room occupancy.
###############################################################################
binary_sensor:
  - platform: template
    sensors:
      office_occupied:
        unique_id: 74406402-58e7-48c0-b0e0-913d050c0348
        friendly_name: "Office Occupied"
        value_template: >-
          {% if is_state('binary_sensor.p1_motion_occupancy', 'on') 
             or is_state('binary_sensor.office_ep1_occupancy', 'on')
             or is_state('binary_sensor.espresense_office_motion', 'on') 
             or is_state('binary_sensor.funhouse_motion_sensor', 'on') %}
             True
          {% else %}
             False
          {% endif %}
        device_class: occupancy

      kitchen_occupied:
        unique_id: 4d065b2d-f162-4a1b-961d-a10cac1a7e06
        friendly_name: "Kitchen Occupied"
        value_template: >-
          {% if is_state('binary_sensor.kn_motion_occupancy', 'on')
             or is_state('binary_sensor.espresense_kitchen_motion', 'on') %}
             True
          {% else %}
             False
          {% endif %}
        device_class: occupancy

      living_room_occupied:
        unique_id: 6a863670-2bd2-4cef-8dd3-d295d99b924e
        friendly_name: "Living Room Occupied"
        value_template: >-
          {% if is_state('binary_sensor.lr_motion_occupancy', 'on') 
             or is_state('binary_sensor.living_room_ep1_occupancy', 'on') 
             or is_state('binary_sensor.living_room_occupancy', 'on') %}
             True
          {% else %}
             False
          {% endif %}
        device_class: occupancy

      main_bedroom_occupied:
        unique_id: 1c0fe49f-9c07-44f3-b4bb-3d8124c7a451
        friendly_name: "Main Bedroom Occupied"
        value_template: >-
          {% if is_state('binary_sensor.mb_motion_occupancy', 'on') 
             or is_state('binary_sensor.main_bedroom_occupancy', 'on') %}
             True
          {% else %}
             False
          {% endif %}
        device_class: occupancy

      guest1_occupied:
        unique_id: 328cdbe4-ca6c-4cdf-8a9b-fa5a308f06b8
        friendly_name: "Guest Bedroom1 Occupied"
        value_template: >-
          {% if is_state('binary_sensor.br1_motion_occupancy', 'on') 
             or is_state('binary_sensor.epl24ea74_occupancy', 'on') %}
             True
          {% else %}
             False
          {% endif %}
        device_class: occupancy

      guest2_occupied:
        unique_id: 7618fb27-7c6c-4bfc-8eb2-aed1d60341ad
        friendly_name: "Guest Bedroom2 Occupied"
        value_template: >-
          {% if is_state('binary_sensor.br2_motion_occupancy', 'on') 
             or is_state('binary_sensor.epl_24e988_occupancy', 'on') %}
             True
          {% else %}
             False
          {% endif %}
        device_class: occupancy

      home_occupied:
        unique_id: b81e3429-4734-4c23-bfbc-121ddcfdc8e5
        friendly_name: "Home Occupied"
        icon_template: >-
          {% if is_state('binary_sensor.home_occupied','True') %}
            mdi:home-account
          {% else %}
            mdi:home-outline
          {% endif %}
        value_template: >-
          {% if is_state('person.gina','home')
             or is_state('person.rodney','home')
             or is_state('person.reannon','home')
             or is_state('person.spencer','home')
             or is_state('person.tori','home')
             or is_state('person.lydia','home') %}
             True
          {% else %}
             False
          {% endif %}
        device_class: occupancy

